### ISSUE TITLE
Error starting up via yarn start

### ISSUE THREAD

**Issue by Gozala** [inkandswitch/pushpin#302]
```sh
yarn start 
yarn run v1.15.2
$ yarn build:clipper-host && ts-node ./scripts/start.ts
$ yarn compile --config-name=clipper-host
$ webpack --config-name=clipper-host
(node:11847) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
Starting type checking service...
Using 1 worker with 2048MB memory limit
Hash: d5ecd8fa4c2faa9e36cf
Version: webpack 4.35.2
Time: 6089ms
Built at: 10/25/2019 10:01:18 AM
Entrypoint clipper-host = clipper-host.js
[./src/apps/clipper-host/JsonBuffer.ts] 1.57 KiB {clipper-host} [built]
[./src/apps/clipper-host/Misc.ts] 4.25 KiB {clipper-host} [built]
[./src/apps/clipper-host/index.ts] 2.3 KiB {clipper-host} [built]
    + 4 hidden modules
ℹ ｢wds｣: Project is running at http://localhost:8080/
ℹ ｢wds｣: webpack output is served from undefined
ℹ ｢wds｣: Content not from webpack is served from /Users/gozala/Projects/pushpin/dist
[hardsource:cb74829a] Node dependencies changed. Building new cache.
Starting type checking service...
Using 1 worker with 2048MB memory limit
[hardsource:a82af425] Node dependencies changed. Building new cache.
Starting type checking service...
Using 1 worker with 2048MB memory limit
Starting type checking service...
Using 1 worker with 2048MB memory limit
Type checking in progress...
ℹ ｢wdm｣: Hash: 8b8e628d8bdf48ef93ae
Version: webpack 4.35.2
Time: 11157ms
Built at: 10/25/2019 10:01:33 AM
                            Asset       Size      Chunks             Chunk Names
    assets/IBMPlexMono-Bold.woff2     36 KiB              [emitted]  
 assets/IBMPlexMono-Regular.woff2   34.7 KiB              [emitted]  
    assets/IBMPlexSans-Bold.woff2   54.8 KiB              [emitted]  
  assets/IBMPlexSans-Italic.woff2   59.2 KiB              [emitted]  
   assets/IBMPlexSans-Medium.woff   79.8 KiB              [emitted]  
  assets/IBMPlexSans-Medium.woff2   58.3 KiB              [emitted]  
 assets/IBMPlexSans-Regular.woff2   54.9 KiB              [emitted]  
assets/IBMPlexSans-SemiBold.woff2   58.6 KiB              [emitted]  
                assets/corner.svg  641 bytes              [emitted]  
        assets/default-avatar.png   11.4 KiB              [emitted]  
                  assets/grid.svg  928 bytes              [emitted]  
          assets/line-awesome.eot    110 KiB              [emitted]  
          assets/line-awesome.svg    424 KiB              [emitted]  
          assets/line-awesome.ttf    110 KiB              [emitted]  
         assets/line-awesome.woff   56.1 KiB              [emitted]  
        assets/line-awesome.woff2   44.1 KiB              [emitted]  
   b03afe0b972f6d54dcda.worker.js   1.64 MiB              [emitted]  
                  background.html  194 bytes              [emitted]  
                    background.js    156 KiB  background  [emitted]  background
                       index.html  180 bytes              [emitted]  
                      renderer.js    795 KiB    renderer  [emitted]  renderer
Entrypoint renderer = renderer.js
Entrypoint background = background.js
[0] multi (webpack)-dev-server/client?http://localhost (webpack)/hot/only-dev-server.js ./src/renderer 52 bytes {renderer} [built]
[1] multi (webpack)-dev-server/client?http://localhost (webpack)/hot/only-dev-server.js ./src/background 52 bytes {background} [built]
[./node_modules/webpack-dev-server/client/index.js?http://localhost] (webpack)-dev-server/client?http://localhost 4.29 KiB {renderer} {background} [built]
[./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.51 KiB {renderer} {background} [built]
[./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.53 KiB {renderer} {background} [built]
[./node_modules/webpack-dev-server/client/utils/createSocketUrl.js] (webpack)-dev-server/client/utils/createSocketUrl.js 2.77 KiB {renderer} {background} [built]
[./node_modules/webpack-dev-server/client/utils/log.js] (webpack)-dev-server/client/utils/log.js 964 bytes {renderer} {background} [built]
[./node_modules/webpack-dev-server/client/utils/reloadApp.js] (webpack)-dev-server/client/utils/reloadApp.js 1.63 KiB {renderer} {background} [built]
[./node_modules/webpack-dev-server/client/utils/sendMessage.js] (webpack)-dev-server/client/utils/sendMessage.js 402 bytes {renderer} {background} [built]
[./node_modules/webpack/hot sync ^\.\/log$] (webpack)/hot sync nonrecursive ^\.\/log$ 170 bytes {renderer} {background} [built]
[./node_modules/webpack/hot/emitter.js] (webpack)/hot/emitter.js 75 bytes {renderer} {background} [built]
[./node_modules/webpack/hot/log-apply-result.js] (webpack)/hot/log-apply-result.js 1.27 KiB {renderer} {background} [built]
[./node_modules/webpack/hot/only-dev-server.js] (webpack)/hot/only-dev-server.js 2.52 KiB {renderer} {background} [built]
[./src/background/index.tsx] 2.27 KiB {background} [built]
[./src/renderer/index.tsx] 3.53 KiB {renderer} [built]
    + 294 hidden modules
Child html-webpack-plugin for "background.html":
              Asset     Size  Chunks  Chunk Names
    background.html  574 KiB       0  
    Entrypoint undefined = background.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./node_modules/html-webpack-plugin/default_index.ejs] 376 bytes {0} [built]
    [./node_modules/lodash/lodash.js] 527 KiB {0} [built]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]
Child html-webpack-plugin for "index.html":
         Asset     Size  Chunks  Chunk Names
    index.html  574 KiB       0  
    Entrypoint undefined = index.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./node_modules/html-webpack-plugin/default_index.ejs] 376 bytes {0} [built]
    [./node_modules/lodash/lodash.js] 527 KiB {0} [built]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]
Child worker:
                             Asset      Size  Chunks             Chunk Names
    b03afe0b972f6d54dcda.worker.js  1.64 MiB    main  [emitted]  main
    Entrypoint main = b03afe0b972f6d54dcda.worker.js
    [./node_modules/pdfjs-dist/build/pdf.worker.js] 1.55 MiB {main} [built]
    [./node_modules/react-pdf/dist/pdf.worker.entry.js] 475 bytes {main} [built]
ℹ ｢wdm｣: Compiled successfully.
No type errors found
Version: typescript 3.6.4
Time: 14506ms
Starting type checking service...
Using 1 worker with 2048MB memory limit
Type checking in progress...
Starting type checking service...
Using 1 worker with 2048MB memory limit
Type checking in progress...
App threw an error during load
Error: Cannot find module './build/bindings/iltorb.node'
Require stack:
- /Users/gozala/Projects/pushpin/node_modules/iltorb/index.js
- /Users/gozala/Projects/pushpin/node_modules/hypermerge/dist/Block.js
- /Users/gozala/Projects/pushpin/node_modules/hypermerge/dist/Actor.js
- /Users/gozala/Projects/pushpin/node_modules/hypermerge/dist/RepoBackend.js
- /Users/gozala/Projects/pushpin/node_modules/hypermerge/dist/Repo.js
- /Users/gozala/Projects/pushpin/node_modules/hypermerge/dist/index.js
- /Users/gozala/Projects/pushpin/dist/main.js
- /Users/gozala/Projects/pushpin/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Function.Module._resolveFilename (/Users/gozala/Projects/pushpin/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.Module._load (internal/modules/cjs/loader.js:531:27)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/gozala/Projects/pushpin/node_modules/iltorb/index.js:10:40)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
No type errors found
Version: typescript 3.6.4
Time: 11627ms
No type errors found
Version: typescript 3.6.4
Time: 11444ms
```

<img width="532" alt="image" src="https://user-images.githubusercontent.com/21236/67589981-ac126400-f70e-11e9-93d4-344989f49eb0.png">

**Comment by pvh** [comment]
The error message here implies that the binary dependencies didn't get compiled. I'm guessing somehow `yarn build-deps` didn't  perform as expected.

**Comment by Gozala** [comment]
I believe it was due to me not having lunched xcode since upgrading to newer macOS.
